# Parte 2: Consolidación de links
### Web Scraping a "Semana" para investigación referente a los cambios climáticos en Colombia

### Paso 1: Importación de librerias

In [1]:
# Importación de librerias
import pandas as pd

# Definición de la clase
class ImportClass:
    
    # Función inicial o constructor
    def __init__(self):
        # lectura de los archivos
            ## encoding='utf-8' es por los caracteres especiales que puede tener los datos
        self.df_new_1 = pd.read_csv(r'df_news_1.csv', encoding='utf-8') 
        self.df_new_2 = pd.read_csv(r'df_news_2.csv', encoding='utf-8')

In [2]:
# 1.1 Instancia del objeto
IC = ImportClass()

In [3]:
# 1.2 Impresión para lectura de datos del (Módulo 1)
IC.df_new_1

,Unnamed: 0,headers_text,headers_link
0,0,África abre sus puertas a inversiones verdes e...,https://www.semana.com/mundo/africa/articulo/a...
1,1,Inundaciones en Brasil: un testimonio impactan...,https://www.semana.com/mundo/articulo/inundaci...
2,2,Responsable climático de la ONU critica fuerte...,https://www.semana.com/mundo/articulo/responsa...
3,3,"“El cambio climático es real y es aterrador”, ...",https://www.semana.com/cultura/cine/articulo/e...
4,4,“Los últimos ocho años fueron los más caluroso...,https://www.semana.com/sostenible/medio-ambien...
...,...,...,...
1487,2359,"Por primera vez, una cámara trampa captó una o...",https://www.semana.com/sostenible/medio-ambien...
1488,2368,Corponor entregó 4.000 palmas de arecas a la D...,https://www.semana.com/sostenible/medio-ambien...
1489,2369,La 'incomprendida' medida ambiental del alcald...,https://www.semana.com/alcalde-de-cali-maurici...
1490,2377,Talas indiscriminadas en la selva de Caquetá p...,https://www.semana.com/talas-de-arboles-en-caq...
1491,2381,Cabo Manglares: un paraíso natural que será pr...,https://www.semana.com/cabo-manglares-un-parai...

In [4]:
# 1.3 Impresión para lectura de datos del (Módulo 2)
IC.df_new_2

,Unnamed: 0,headers_text,headers_link
0,0,La CVC sembró el árbol de mangle número 35 mil...,https://www.semana.com/sostenibilidad/medio-am...
1,1,Con la siembra de 150.000 árboles reforestarán...,https://www.semana.com/sostenible/medio-ambien...
2,2,Textilera colombiana Lafayette sembrará 8.000 ...,https://www.semana.com/sostenibilidad/medio-am...
3,3,Se sembraron 10 mil árboles nativos para resta...,https://www.semana.com/medio-ambiente/articulo...
4,4,Inician la siembra de un millón de árboles en ...,https://www.semana.com/sostenible/medio-ambien...
...,...,...,...
1056,1442,Lecciones del coronavirus en tiempos de cambio...,https://www.semana.com/medio-ambiente/articulo...
1057,1447,Neutralidad del carbono: ¿qué se requiere real...,https://www.semana.com/medio-ambiente/articulo...
1058,1457,¿Cuáles son los países que avanzan realmente h...,https://www.semana.com/cuales-son-los-paises-q...
1059,1458,El cambio climático preocupa a los colombianos...,https://www.semana.com/medio-ambiente/articulo...
1060,1459,20 años le quedan a la humanidad para evitar e...,https://www.semana.com/medio-ambiente/articulo...

### Paso 2: Consolidación de Dataframes

In [5]:
# 2.1 Consolidación en un único dataframe de todas las noticias para su procesamiento
df_consolidated_no_clean = pd.concat([IC.df_new_1, IC.df_new_2])

# 2.2 Impresión del DataFrame únificado
df_consolidated_no_clean

,Unnamed: 0,headers_text,headers_link
0,0,África abre sus puertas a inversiones verdes e...,https://www.semana.com/mundo/africa/articulo/a...
1,1,Inundaciones en Brasil: un testimonio impactan...,https://www.semana.com/mundo/articulo/inundaci...
2,2,Responsable climático de la ONU critica fuerte...,https://www.semana.com/mundo/articulo/responsa...
3,3,"“El cambio climático es real y es aterrador”, ...",https://www.semana.com/cultura/cine/articulo/e...
4,4,“Los últimos ocho años fueron los más caluroso...,https://www.semana.com/sostenible/medio-ambien...
...,...,...,...
1056,1442,Lecciones del coronavirus en tiempos de cambio...,https://www.semana.com/medio-ambiente/articulo...
1057,1447,Neutralidad del carbono: ¿qué se requiere real...,https://www.semana.com/medio-ambiente/articulo...
1058,1457,¿Cuáles son los países que avanzan realmente h...,https://www.semana.com/cuales-son-los-paises-q...
1059,1458,El cambio climático preocupa a los colombianos...,https://www.semana.com/medio-ambiente/articulo...
1060,1459,20 años le quedan a la humanidad para evitar e...,https://www.semana.com/medio-ambiente/articulo...

### Paso 3: Limpieza del Dataframe consolidado

In [6]:
# 3.1. Limpieza del DataFrame según la columna de links df_consolidated_no_clean.drop_duplicates(subset=["headers_link"])
# 3.2. Eliminación de columna que se creo en por error "Unnamed: 0" .drop('Unnamed: 0', axis=1)
# 3.3. Reseteo de index por la acción de combinación de DataFrames .reset_index().drop(['index'], axis=1)
df_consolidated_clean = df_consolidated_no_clean.drop_duplicates(subset=["headers_link"]).drop('Unnamed: 0', axis=1).reset_index().drop(['index'], axis=1)

In [7]:
# Impresión del Dataframe limpio y consolidado
df_consolidated_clean

,headers_text,headers_link
0,África abre sus puertas a inversiones verdes e...,https://www.semana.com/mundo/africa/articulo/a...
1,Inundaciones en Brasil: un testimonio impactan...,https://www.semana.com/mundo/articulo/inundaci...
2,Responsable climático de la ONU critica fuerte...,https://www.semana.com/mundo/articulo/responsa...
3,"“El cambio climático es real y es aterrador”, ...",https://www.semana.com/cultura/cine/articulo/e...
4,“Los últimos ocho años fueron los más caluroso...,https://www.semana.com/sostenible/medio-ambien...
...,...,...
2039,Cinco nuevos saltamontes descubiertos en las s...,https://www.semana.com/medio-ambiente/articulo...
2040,Descuartizan oso para amenazar a Parques Nacio...,https://www.semana.com/oso-de-anteojos-descuar...
2041,El río que no se deja llevar por la corriente\...,https://www.semana.com/el-rio-que-no-se-deja-l...
2042,¿Qué hacer con la gente que vive en los páramo...,https://www.semana.com/paramos-que-hacer-con-l...
2043,Dos mamíferos y 63 aves fueron acogidos por el...,https://www.semana.com/sostenible/medio-ambien...

In [8]:
# 3.4 Generación de archivo .csv
df_consolidated_clean.to_csv("df_consolidated_clean.csv")