### Comisión Económica Para América Latina y el Caribe 
##### (Contexto)
Se refiere a la proporción de la oferta interna total efectiva de energía que es obtenida de fuentes energéticas renovables. La oferta interna total efectiva corresponde a la oferta de energía primaria, más la oferta de energía secundaria, menos la producción de energía secundaria. La oferta interna de una fuente energética dada (por ejemplo de las fuentes renovables) corresponde a la cantidad de energía producida, más la cantidad importada, menos la cantidad exportada, más la cantidad de variación de inventarios, menos cantidad de energía no aprovechada, menos la cantidad de pérdidas de dicha fuente energética.

In [1]:
# Importación de librerias
import dash
from dash import Dash, html, dcc, callback, Output, Input
import plotly.express as px
import pandas as pd

# Definición de la clase
class ImportClass:
    
    # Función inicial o constructor
    def __init__(self):
        # lectura de los archivos
            ## encoding='utf-8' es por los caracteres especiales que puede tener los datos
        
        # Lectura en hoja 1
        self.df_pe = pd.read_excel(r'PROPORCION_ENERGETICA.xlsx', sheet_name='PROPORCION');
                # Definición de los estilos como variables de clase
        
        # Estilos generales para la tabla
        self.table_style = {
            'border': '1px solid black',
            'border-collapse': 'collapse',
            'width': '100%',
        }
        
        # Estilos generales para los encabezados
        self.header_style = {
            'background-color': '#3c4b64',
            'color': '#FFFFFF',
            'font-weight': 'bold',
            'text-transform': 'uppercase',
        }
        
        # Estilos generales para las celdas
        self.cell_style = {
            'border': '1px solid black',
            'padding': '8px',
            'text-align': 'left',
        }
    
    
     # Definición de función para creación de gráfico especial para el DataFrame 1
    def create_dash_app(self, df, title, port):

        years = df['AÑO'].tolist()
        
        app = dash.Dash(__name__)
        
        df_columns = df.columns.str.replace("_", " ")

        app.layout = html.Div([
            html.H5(children=title.replace("_", " "), style={'textAlign': 'center'}),


            dcc.Dropdown(options=[{'label': indicator, 'value': indicator} for indicator in df_columns[1:]],
                         value=df_columns[1],  # Establecemos el valor inicial
                         id='dropdown-selection'),

            dcc.Graph(id='graph-content'),

            html.Div(id='filtered-records'),
        ])
        
        @callback(
            Output('graph-content', 'figure'),
            Output('filtered-records', 'children'),  # Mostrar la tabla debajo del gráfico
            Input('dropdown-selection', 'value')
        )
        def update_graph_and_table(value):

            value = value.replace(" ", "_")
            
            # Crea un DataFrame a partir de las listas
            df_1 = pd.DataFrame({'Año': years, 'Valor': df[value].tolist()})
            
            fig = px.bar(df_1, x='Año', y='Valor')
            
            fig.update_layout(title='Gráfico',
                  xaxis_title='Años',
                  yaxis_title='Valores')
            
            col_0 = df_1.columns[0] # Año
            col_1 = df_1.columns[1] # Valor
            
            number_value_table = html.Table(
                [html.Tr([html.Th(col, style=self.header_style) for col in ['AÑO', 'VALOR']])] +
                [html.Tr([html.Td(df_1.iloc[i][col], style=self.cell_style) for col in [col_0, col_1]]) for i in range(len(df_1))],
                style=self.table_style
            )

            return fig, number_value_table

        
        if __name__ == '__main__':
            app.run(port=port)

In [2]:
# 1.1 Instancia del objeto
IC = ImportClass()

In [3]:
# 2.1 Impresión para lectura de datos del archivo
IC.df_pe

,AÑO,HIDROENERGÍA,LEÑA,BAGAZO,RESIDUOS,ALCOHOL_CARBURANTE,BIODIESEL,OFERTA_INTERNA_DE_ENERGÍA_OBTENIDA_DE_FUENTES_RENOVABLES_(TCAL),OFERTA_INTERNA_TOTAL_EFECTIVA_DE_ENERGÍA_(TCAL),PROPORCIÓN_DE_LA_OFERTA_ENERGÉTICA_QUE_ES_SUMINISTRADA_POR_FUENTES_RENOVABLES_(%)
0,1975,7316.978900,31407.9888,8745.100000,494.400000,0.000000,0.000000,47964.467700,143799.072771,33.355200
1,1976,8401.545200,33572.6280,9378.460000,471.500000,0.000000,0.000000,51824.133200,171627.212637,30.195755
2,1977,10680.168000,34400.0160,8936.200000,519.300000,0.000000,0.000000,54535.684000,169923.189736,32.094315
3,1978,12340.398000,35248.1400,9711.520000,523.300000,0.000000,0.000000,57823.358000,171025.596865,33.809768
4,1979,13541.216000,37408.6000,10210.200000,583.000000,0.000000,0.000000,61743.016000,200094.045905,30.856998
5,1980,18506.029200,37799.3976,10750.740000,608.300000,0.000000,0.000000,67664.466800,203317.373793,33.280219
6,1981,14764.738000,38616.4573,10448.429400,738.892000,0.000000,0.000000,64568.516700,207519.336639,31.114458
7,1982,15581.910000,39209.8832,10692.500000,845.766000,0.000000,0.000000,66330.059200,216570.967273,30.627401
8,1983,18788.378100,39593.2419,11009.180000,1091.300000,0.000000,0.000000,70482.100000,237076.860639,29.729641
9,1984,17399.090000,39780.1000,11675.300000,1222.900000,0.000000,0.000000,70077.390000,251204.651130,27.896534
10,1985,18732.176000,39784.0241,12654.460000,1245.400000,0.000000,0.000000,72416.060100,256922.097707,28.185999
11,1986,21725.148000,37910.0520,12383.280000,1379.200000,0.000000,0.000000,73397.680000,256179.243473,28.650908
12,1987,24142.608000,38482.1640,12676.300000,1453.300000,0.000000,0.000000,76754.372000,258545.807939,29.686953
13,1988,25228.960000,39155.7600,13289.193200,1615.695600,0.000000,0.000000,79289.608800,253692.364412,31.254235
14,1989,24380.737500,37943.2000,13475.731500,1770.007500,0.000000,0.000000,77569.676500,258889.356405,29.962482
15,1990,24325.171600,37534.4656,13913.139200,1925.790400,0.000000,0.000000,77698.566800,211785.813999,36.687333
16,1991,28386.020000,36725.6843,14347.476500,2081.411700,0.000000,0.000000,81540.592500,233284.155792,34.953335
17,1992,28937.639200,35828.9352,7199.920000,2232.300000,0.000000,0.000000,74198.794400,201588.586913,36.807041
18,1993,29863.465600,34857.7849,7670.208000,2492.884000,0.000000,0.000000,74884.342500,206563.120937,36.252523
19,1994,30221.576000,33825.8000,7816.172000,2640.870000,0.000000,0.000000,74504.418000,203916.801717,36.536674
20,1995,31010.998000,32469.4768,7972.692000,2781.128000,0.000000,0.000000,74234.294800,203847.807830,36.416528
21,1996,31738.895200,32360.7600,8004.178000,2911.942000,0.000000,0.000000,75015.775200,226009.995472,33.191353
22,1997,32439.630000,30691.0800,8179.808000,3031.596000,0.000000,0.000000,74342.114000,243574.544100,30.521299
23,1998,33408.926000,28501.5600,8404.760000,3138.374000,0.000000,0.000000,73453.620000,267288.259600,27.481050
24,1999,32679.812500,26998.9200,8180.536000,3220.000000,0.000000,0.000000,71079.268500,276530.270982,25.703974
25,2000,34325.371200,27116.0936,8263.892000,3306.438000,0.000000,0.000000,73011.794800,274715.828953,26.577207
26,2001,35227.994600,26038.1313,9000.082000,3364.292000,0.000000,0.000000,73630.499900,265843.939320,27.696889
27,2002,37844.254400,25007.8672,9520.459860,3402.406000,0.000000,0.000000,75774.987460,299572.862280,25.294343
28,2003,38404.752300,24048.0000,9664.200000,3419.064000,0.000000,0.000000,75536.016300,297297.109173,25.407585
29,2004,41615.820000,23362.6000,9727.263240,3346.950000,0.000000,0.000000,78052.633240,311647.330214,25.045179
30,2005,40750.240000,22284.0000,9426.718800,3328.885900,163.685000,0.000000,75953.529700,326566.607090,23.258205
31,2006,41927.345600,21402.0000,11566.599699,3286.171200,1237.142592,0.000000,79419.259091,342834.896245,23.165454
32,2007,42583.063900,21394.8000,8816.745799,3217.173300,1372.428000,0.000000,77384.210999,318694.805387,24.281604
33,2008,43164.232800,21387.6000,8995.494099,3078.000000,1289.616000,1056.442940,78971.385839,340609.656573,23.185304
34,2009,42028.200000,21387.6000,9898.933235,2993.797500,1693.467039,2084.277855,80086.275628,334139.187167,23.967939
35,2010,41362.498571,21387.6000,10136.561584,2851.958963,1447.547939,3263.690450,80449.857507,354489.283817,23.508483
36,2011,43410.925700,21387.6000,12318.359037,2645.697700,1739.379368,4372.541309,85874.503114,326214.945815,26.324515
37,2012,48714.613877,22492.8000,11343.278488,2632.756493,1826.034203,4674.151552,91683.634613,344886.580645,26.583706

In [4]:
# Ejemplo de uso:
df_pe = IC.df_pe  # Reemplaza esto con tu DataFrame
IC.create_dash_app(df_pe, 'COMISIÓN_ECONÓMICA_PARA_AMÉRICA_LATINA_Y_EL_CARIBE', 8056)