### Consumo total de hidroclorofluorocarbonos (HCFC)
##### (Contexto)
Es el consumo nacional aparente de Hidroclorofluorocarbonos (HCFC), sustancias controladas por el Protocolo de Montreal, correspondiente a la suma de la producción más las importaciones menos las exportaciones

In [1]:
 # Importación de librerias
import dash
from dash import Dash, html, dcc, callback, Output, Input
import plotly.express as px
import pandas as pd

# Definición de la clase
class ImportClass:
    
    # Función inicial o constructor
    def __init__(self):
        # lectura de los archivos
            ## encoding='utf-8' es por los caracteres especiales que puede tener los datos
        
        # Lectura en hoja 1
        self.df_hcfc = pd.read_excel(r'COSUMO_DE_HCFC.xlsx');
                # Definición de los estilos como variables de clase
        
        # Estilos generales para la tabla
        self.table_style = {
            'border': '1px solid black',
            'border-collapse': 'collapse',
            'width': '100%',
        }
        
        # Estilos generales para los encabezados
        self.header_style = {
            'background-color': '#3c4b64',
            'color': '#FFFFFF',
            'font-weight': 'bold',
            'text-transform': 'uppercase',
        }
        
        # Estilos generales para las celdas
        self.cell_style = {
            'border': '1px solid black',
            'padding': '8px',
            'text-align': 'left',
        }
    
    
     # Definición de función para creación de gráfico especial para el DataFrame 1
    def create_dash_app(self, df, title, port):

        years = df['AÑO'].tolist()
        
        app = dash.Dash(__name__)
        
        df_columns = df.columns.str.replace("_", " ")

        app.layout = html.Div([
            html.H5(children=title.replace("_", " "), style={'textAlign': 'center'}),


            dcc.Dropdown(options=[{'label': indicator, 'value': indicator} for indicator in df_columns[1:]],
                         value=df_columns[1],  # Establecemos el valor inicial
                         id='dropdown-selection'),

            dcc.Graph(id='graph-content'),

            html.Div(id='filtered-records'),
        ])
        
        @callback(
            Output('graph-content', 'figure'),
            Output('filtered-records', 'children'),  # Mostrar la tabla debajo del gráfico
            Input('dropdown-selection', 'value')
        )
        def update_graph_and_table(value):

            value = value.replace(" ", "_")
            
            # Crea un DataFrame a partir de las listas
            df_1 = pd.DataFrame({'Año': years, 'Valor': df[value].tolist()})
            
            fig = px.bar(df_1, x='Año', y='Valor')
            
            fig.update_layout(title='Gráfico',
                  xaxis_title='Años',
                  yaxis_title='Valores')
            
            col_0 = df_1.columns[0] # Año
            col_1 = df_1.columns[1] # Valor
            
            number_value_table = html.Table(
                [html.Tr([html.Th(col, style=self.header_style) for col in ['AÑO', 'VALOR']])] +
                [html.Tr([html.Td(df_1.iloc[i][col], style=self.cell_style) for col in [col_0, col_1]]) for i in range(len(df_1))],
                style=self.table_style
            )

            return fig, number_value_table

        
        if __name__ == '__main__':
            app.run(port=port)

In [2]:
# 1.1 Instancia del objeto
IC = ImportClass()

In [3]:
# 2.1 Impresión para lectura de datos del archivo
IC.df_hcfc

     AÑO  COSUMO_DE_HCFC
0   2000            0.00
1   2001          101.40
2   2002           89.93
3   2003          109.17
4   2004          123.73
5   2005          152.08
6   2006          160.59
7   2007          206.17
8   2008          206.24
9   2009          209.66
10  2010          241.47
11  2011          220.50
12  2012          285.50
13  2013          176.65
14  2014          156.07
15  2015          165.29

In [4]:
# Ejemplo de uso:
df_hcfc = IC.df_hcfc  # Reemplaza esto con tu DataFrame
IC.create_dash_app(df_hcfc, 'CONSUMO_TOTAL_DE_HIDROCLOROFLUOROCARBONOS_(HCFC)', 8050)