In [1]:
# Importación de librerias
import dash
from dash import Dash, html, dcc, callback, Output, Input
import plotly.express as px
import pandas as pd

# Definición de la clase
class ImportClass:
    
    # Función inicial o constructor
    def __init__(self):
        # lectura de los archivos
            ## encoding='utf-8' es por los caracteres especiales que puede tener los datos
        
        # Lectura en hoja 1
        self.df_1901_1930 = pd.read_csv(r'temperature_1901_1930_br_colombia.csv');
        self.df_1931_1960 = pd.read_csv(r'temperature_1931_1960_br_colombia.csv');        
        self.df_1961_1990 = pd.read_csv(r'temperature_1961_1990_br_colombia.csv');        
        self.df_1991_2020 = pd.read_csv(r'temperature_1991_2020_br_colombia.csv');

In [2]:
# 1.1 Instancia del objeto
IC = ImportClass()

In [3]:
IC.df_1901_1930

,,,,Category,Min-Temperature,Mean-Temperature,Max-Temperature,Precipitation
Jan,19,95,25,17,30,44,102,54.0
Feb,20,24,25,44,30,68,116,38.0
Mar,20,72,25,55,30,43,181,59.0
Apr,20,87,25,36,29,91,242,64.0
May,20,58,24,92,29,3,299,6.0
Jun,20,45,24,59,28,78,280,73.0
Jul,19,93,24,4,28,92,262,96.0
Aug,19,96,24,63,29,34,233,81.0
Sep,20,12,24,93,29,78,234,8.0
Oct,20,46,25,29,58,235,6,NaN
Nov,20,6,25,2,29,48,220,74.0
Dec,20,37,25,5,29,79,152,6.0